import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.whatToDo': 'What to Do',
    'nav.whereToStay': 'Where to Stay',
    'nav.events': 'Events',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    
    // Home Page
    'home.hero.title': 'Cabeceras',
    'home.hero.subtitle': 'Everyday life in a rural Costa Rican community',
    'home.hero.tagline': 'A meaningful stop near Monteverde',
    'home.whereWeAre.title': 'Where We Are',
    'home.whereWeAre.description': 'Cabeceras is located 25 minutes from Monteverde, along the road between Monteverde and La Fortuna.',
    'home.communityWalk.title': 'Start with the Community Walk',
    'home.communityWalk.description1': "You'll pass local gathering places, farms, and viewpoints, and learn how people live and work here.",
    'home.communityWalk.description2': 'Request a free local guide — youth and women from the community sharing their town.',
    'home.communityWalk.learnButton': 'Learn About the Walk',
    'home.communityWalk.requestButton': 'Request a Guide',
    'home.moreWays.title': 'More Ways to Connect',
    'home.moreWays.description': 'Cook with local families, learn traditional crafts, watch the sunset, or hang out where locals gather',
    'home.moreWays.photo1': 'Cooking together',
    'home.moreWays.photo2': 'Celebrations',
    'home.moreWays.button': 'See All Experiences',
    'home.testimonials.title': 'What Visitors Share',
    'home.testimonials.subtitle': 'Reflections from people who spent time in Cabeceras',
    'home.testimonial1': 'The community tour with our local guide was incredible. We learned so much about real Costa Rican life — from coffee farming to local traditions. It felt authentic and meaningful.',
    'home.testimonial2': 'The cooking class with Doña Luz was the highlight of our trip. We made traditional dishes in her home kitchen and heard amazing stories. This is what travel should be about.',
    'home.testimonial3': 'The sunset at Finitos Lookout was breathtaking, and hanging out at Mikancha café with locals was so relaxing. Cabeceras showed us a side of Costa Rica we never would have found otherwise.',
    'home.planVisit.title': 'Plan Your Visit',
    'home.planVisit.description': "Whether you're passing through or staying a while, Cabeceras welcomes you",
    'home.planVisit.accommodationButton': 'Find Accommodation',
    'home.planVisit.contactButton': 'Get in Touch',

    // What to Do Page
    'experiences.hero.title': 'What to Do in Cabeceras',
    'experiences.hero.subtitle': 'Ways to spend time here',
    'experiences.communityWalk.title': 'The Community Walk',
    'experiences.communityWalk.description': 'Start at the Salón Comunal, pass the school and hillside garden, visit the old tree where toucans gather, walk up to the lookout point, and loop through a coffee farm. Self-guided anytime, or request a local guide. Guides are youth and women from the community who practice English and share their town.',
    'experiences.communityWalk.duration': '~45 minutes',
    'experiences.communityWalk.difficulty': 'Easy to Moderate',
    'experiences.communityWalk.aboutButton': 'About the Walk',
    'experiences.communityWalk.guideButton': 'Request a Guide',
    'experiences.cooking.title': 'Cooking with Doña Luz',
    'experiences.cooking.description': 'Join Doña Luz in her home to make empanadas, bread, and fresh sugarcane juice using her traditional mill. Enjoy coffee from her farm, mountain views, and stories shared at a relaxed pace. Contact Doña Luz directly via WhatsApp to arrange a time. Plan 24–48 hours ahead when possible.',
    'experiences.cooking.duration': '3 hours',
    'experiences.cooking.difficulty': 'All levels',
    'experiences.cooking.button': 'Contact to Arrange',
    'experiences.embroidery.title': 'Embroidery with Doña Margarita',
    'experiences.embroidery.description': 'Create your own cloud forest souvenir while learning patterns inspired by Costa Rican nature. Doña Margarita and other women in the community will guide you. Contact Doña Margarita directly via WhatsApp to arrange a time. Plan 24-48 hours ahead when possible.',
    'experiences.embroidery.duration': '2-3 hours',
    'experiences.embroidery.difficulty': 'All levels',
    'experiences.mikancha.title': 'Mikancha',
    'experiences.mikancha.description': 'Watch soccer games (mejengas), play pool, grab food, and hang out where community members spend their free time. No reservation needed — just show up and see who\'s around.',
    'experiences.mikancha.duration': 'Flexible',
    'experiences.mikancha.difficulty': 'Easy',
    'experiences.mikancha.note': 'No reservation needed — just stop by',
    'experiences.lookout.title': 'Finitos Lookout',
    'experiences.lookout.description': 'Walk through gardens with valley views. Best at sunset when the sky transforms. No hiking required — the lookout is easily accessible. Recommended donation: ₡2,000 per person. No reservation needed.',
    'experiences.lookout.duration': '1-2 hours',
    'experiences.lookout.difficulty': 'Easy',

    // Tour Page
    'tour.hero.title': 'Community Tour',
    'tour.hero.subtitle': 'See how people live and work in Cabeceras',
    'tour.about.title': 'About the Tour',
    'tour.about.description1': 'Our community tour takes you through the heart of Cabeceras, sharing the story of our town, its people, and how we live. Learn about our main industries (dairy farms and coffee plantations), how local government and committees function, and how things are changing in our community.',
    'tour.about.description2': 'You can do this as a self-guided tour using our map, but we strongly recommend booking a free local guide. Our guide program was designed to help local youth and women develop confidence, leadership skills, and English language acquisition while facilitating a symbiotic exchange between travelers and locals.',
    'tour.stats.duration': 'Duration',
    'tour.stats.durationValue': '~45 minutes',
    'tour.stats.difficulty': 'Difficulty',
    'tour.stats.difficultyValue': 'Easy to Moderate',
    'tour.stats.cost': 'Cost',
    'tour.stats.costValue': 'Free',
    'tour.route.title': 'Self-Guided Tour Route',
    'tour.route.description': 'Follow these stops at your own pace. Look for signs along the way, or download our map for offline use.',
    'tour.stop1.name': 'Salón Comunal',
    'tour.stop1.description': 'Begin your walk at the community center, with open views of the town. Read about the history of Cabeceras, daily life today, and get oriented.',
    'tour.stop2.name': 'Local School',
    'tour.stop2.description': 'Pass by the elementary school and learn about education in the community and the lives of young people who grow up here.',
    'tour.stop3.name': 'Hillside Garden',
    'tour.stop3.description': 'Walk past a landscaped hillside created by the community, with the option to walk up for views over the town.',
    'tour.stop4.name': 'The Church',
    'tour.stop4.description': 'Pass by the church and read about the role of religion in the region and community life.',
    'tour.stop5.name': 'The Old Tree',
    'tour.stop5.description': 'Visit a long-standing tree that has been part of the community for generations. Look for toucans and other birds in the branches, and read about local wildlife and how this area differs from nearby Monteverde.',
    'tour.stop6.name': 'Cubiertas Lookout',
    'tour.stop6.description': 'Walk up to a viewpoint overlooking the valley and surrounding mountains.',
    'tour.stop7.name': 'Coffee Farm Loop',
    'tour.stop7.description': 'Walk through a coffee farm and a forested area, looping back to your starting point. Learn about coffee production and its role in the local economy.',
    'tour.accessibility.title': 'Accessibility Note',
    'tour.accessibility.description': 'The Coffee Farm Loop (stop 7) includes a short, steep section with uneven footing. If needed, you can turn around and return the way you came; the main route remains complete.',
    'tour.map.title': 'Tour Map',
    'tour.map.downloadButton': 'Download Map',
    'tour.guide.title': 'Want a Local Guide?',
    'tour.guide.description1': 'Youth and women from the community can walk with you and share stories, answer questions, and help you understand what you are seeing.',
    'tour.guide.description2': 'Guides are free — the program helps locals practice English and build confidence while creating meaningful exchanges with visitors.',
    'tour.guide.button': 'Request a Guide',

    // Where to Stay Page
    'stay.hero.title': 'Where to Stay',
    'stay.hero.subtitle': "A peaceful local community, just beyond Monteverde's busy center",
    'stay.camping.name': 'Camping Finito',
    'stay.camping.description': 'Fall asleep under the stars, wake up to mountain views. Basic facilities. Good for budget travelers and nature lovers.',
    'stay.camping.amenity1': 'Tent sites',
    'stay.camping.amenity2': 'Shared facilities',
    'stay.camping.amenity3': 'Lookout access',
    'stay.casaToucan.name': "El Tucan's House",
    'stay.casaToucan.description': 'Wake up to tropical birds, eat traditional meals, and feel like part of the family. The hosts share stories and local knowledge.',
    'stay.casaToucan.amenity1': 'Home-cooked meals',
    'stay.casaToucan.amenity2': 'Private rooms',
    'stay.casaToucan.amenity3': 'Shared bathrooms',
    'stay.casaAlma.name': 'Villa Alma de Campo',
    'stay.casaAlma.description': 'A modern, comfortable home with sweeping mountain views and thoughtful, luxurious details.',
    'stay.casaAlma.amenity1': 'Mountain views',
    'stay.casaAlma.amenity2': 'Modern amenities',
    'stay.casaAlma.amenity3': 'Luxurious details',
    'stay.contactButton': 'Contact to Book',
    'stay.testimonials.title': 'Why Stay in Cabeceras?',
    'stay.testimonials.subtitle': 'Hear from travelers who chose to stay in our community',
    'stay.testimonial1': "Camping at Finitos was an adventure! Waking up to mountain views and being so close to the lookout point was amazing. Budget-friendly and unforgettable.",
    'stay.testimonial2': "Staying at Casa Toucan felt like being part of the family. The home-cooked meals were incredible, and we learned so much about local life. It was the perfect base between Monteverde and La Fortuna.",
    'stay.testimonial3': "Casa Alma was a peaceful retreat after the crowds in Monteverde. The garden views, the quiet mornings, and the genuine hospitality made us extend our stay by two nights.",

    // Events Page
    'events.hero.title': 'Community Events',
    'events.intro.description1': 'These are real gatherings that happen in Cabeceras as part of everyday community life. Visitors are welcome to attend and experience how locals come together.',
    'events.intro.description2': 'Events may change or be canceled. Check with us closer to your visit date for current information.',
    'events.upcoming.title': 'Upcoming Events',
    'events.recurring.title': 'Recurring Activities',
    'events.submit.title': 'Community Members',
    'events.submit.description': 'Have an event to share? Let us know about upcoming community gatherings, celebrations, or activities.',
    'events.submit.button': 'Submit an Event',
    'events.event1.title': 'Coffee Harvest Festival',
    'events.event1.date': 'December 15-17, 2024',
    'events.event1.time': 'All day',
    'events.event1.location': 'Various locations throughout town',
    'events.event1.description': 'Annual celebration of the coffee harvest season. Tours of local farms, traditional music, and community meals.',
    'events.event2.title': 'Youth Art Exhibition',
    'events.event2.date': 'March 20-25, 2025',
    'events.event2.time': '10:00 AM - 6:00 PM',
    'events.event2.location': 'Community Center',
    'events.event2.description': 'Student artwork from the local school on display. Paintings, crafts, and creative projects.',
    'events.event3.title': 'Independence Day Celebration',
    'events.event3.date': 'September 15, 2025',
    'events.event3.time': '9:00 AM - 8:00 PM',
    'events.event3.location': 'Salón Comunal',
    'events.event3.description': 'Costa Rican Independence Day festivities with traditional food, music, and the lantern parade.',
    'events.recurring1.title': 'Community Market',
    'events.recurring1.schedule': 'Every Saturday',
    'events.recurring1.time': '8:00 AM - 2:00 PM',
    'events.recurring1.location': 'Salón Comunal',
    'events.recurring1.description': 'Local vendors sell fresh produce, crafts, and homemade goods.',
    'events.recurring2.title': 'Traditional Music Night',
    'events.recurring2.schedule': 'First Friday of each month',
    'events.recurring2.time': '7:00 PM - 10:00 PM',
    'events.recurring2.location': 'Mikancha Café',
    'events.recurring2.description': 'Live music performances by local musicians. Open to everyone.',
    'events.recurring3.title': 'Community Meeting',
    'events.recurring3.schedule': 'Second Tuesday of each month',
    'events.recurring3.time': '6:00 PM',
    'events.recurring3.location': 'Salón Comunal',
    'events.recurring3.description': 'Open town meeting to discuss community matters. Visitors welcome to observe.',

    // FAQ Page
    'faq.hero.title': 'Frequently Asked Questions',
    'faq.hero.subtitle': 'Everything you need to know about visiting Cabeceras',
    'faq.question1': 'Is the community tour really free?',
    'faq.answer1': 'Yes, it\'s completely free as you are supporting locals in capacity building/developing important skills. We also appreciate you having the curiosity and taking the time to learn about our town and people. Feel free to give a small tip to your guide if you enjoyed the tour, but it is not expected.',
    'faq.question2': 'How do I get to Cabeceras?',
    'faq.answer2': 'Cabeceras is 25 minutes from Monteverde, on the main route between Monteverde and La Fortuna. You can reach us by car or arrange transportation through your accommodation.',
    'faq.question3': 'Do I need to book experiences in advance?',
    'faq.answer3': 'While the self-guided community tour is always available, we recommend booking cooking classes, workshops, and guided experiences at least 24-48 hours in advance to ensure availability. Contact us via WhatsApp or email to arrange.',
    'faq.question4': 'What should I bring for the tour?',
    'faq.answer4': 'Comfortable walking shoes, sun protection, water, and a camera are recommended. The tour involves moderate walking on unpaved paths. We also suggest bringing small bills if you wish to make purchases at local shops or leave donations.',
    'faq.question5': 'Is Cabeceras suitable for families with children?',
    'faq.answer5': 'Absolutely! Cabeceras is very family-friendly. Children enjoy interacting with local kids, learning about farming, and exploring nature. The cooking classes and craft workshops are particularly popular with families.',
    'faq.question6': 'How long should I plan to spend in Cabeceras?',
    'faq.answer6': 'Most visitors spend 2-4 hours on the community tour, but we recommend staying at least a full day to truly experience local life. Many travelers choose to stay overnight in one of our guesthouses to fully immerse themselves.',
    'faq.question7': 'What languages are spoken?',
    'faq.answer7': 'Spanish is the primary language, but many community members speak basic English. Our guides have varying levels of English, so we invite guests to come with an open mind! Language differences often lead to memorable and creative exchanges.',
    'faq.question8': 'How does tourism benefit the community?',
    'faq.answer8': 'All tourism activities directly support local families, fund youth education programs, provide income for women artisans, and help maintain community infrastructure. We practice ethical, community-led tourism that empowers residents.',
    'faq.question9': 'Can I volunteer in Cabeceras?',
    'faq.answer9': 'We occasionally have volunteer opportunities, especially for those with teaching, agricultural, or community development skills. Contact us to discuss current needs and how you might contribute during your visit.',
    'faq.question10': 'What is the weather like?',
    'faq.answer10': 'Cabeceras has a tropical climate and is generally drier and sunnier than Monteverde, while being cooler than La Fortuna due to its elevation. Days are usually warm and comfortable, with cooler mornings and evenings.',
    'faq.question11': 'Are there ATMs or banks in Cabeceras?',
    'faq.answer11': 'Cabeceras is a small town without ATMs or banks. We recommend bringing cash from Monteverde or La Fortuna. Some accommodations and experiences accept credit cards, but cash is preferred.',
    'faq.question12': 'Is it safe to visit Cabeceras?',
    'faq.answer12': 'Yes, Cabeceras is a very safe community. Like anywhere, use common sense with your belongings. The community is welcoming and looks out for visitors. Our guides and hosts will help ensure you have a safe, enjoyable experience.',
    'faq.stillQuestions.title': 'Still Have Questions?',
    'faq.stillQuestions.description': "We're here to help! Contact us and we'll be happy to answer any questions about visiting Cabeceras.",
    'faq.stillQuestions.button': 'Get in Touch',

    // Contact Page
    'contact.hero.title': 'Get in Touch',
    'contact.hero.subtitle': 'Questions about visiting Cabeceras?',
    'contact.form.title': 'Send a Message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.message': 'Message',
    'contact.form.namePlaceholder': 'Your name',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.messagePlaceholder': 'What would you like to know?',
    'contact.form.submitButton': 'Send Message',
    'contact.form.nameError': 'Name is required',
    'contact.form.emailError': 'Email is required',
    'contact.form.emailInvalid': 'Please enter a valid email',
    'contact.form.messageError': 'Message is required',
    'contact.form.successMessage': 'Thank you for your message! We will get back to you soon.',
    'contact.other.title': 'Other Ways to Reach Us',
    'contact.email.title': 'Email',
    'contact.email.description': 'We typically respond within 24 hours',
    'contact.whatsapp.title': 'WhatsApp',
    'contact.whatsapp.description': 'Fastest way to reach us, especially for booking guides or checking availability',
    'contact.whatsapp.button': 'Message on WhatsApp',
    'contact.askAbout.title': 'What to Ask About',
    'contact.askAbout.item1': 'Guide availability for the community walk',
    'contact.askAbout.item2': 'Booking cooking or embroidery classes',
    'contact.askAbout.item3': 'Accommodation recommendations',
    'contact.askAbout.item4': 'Transportation and directions',
    'contact.askAbout.item5': 'Current events or activities',

    // Footer
    'footer.description': 'Authentic Costa Rican experiences that empower our community and create meaningful connections with travelers.',
    'footer.quickLinks': 'Quick Links',
    'footer.connect': 'Connect With Us',
    'footer.copyright': 'Cabeceras Community Tourism. All rights reserved.',
    'footer.tagline': 'Built with love for authentic cultural exchange.',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.whatToDo': 'Qué Hacer',
    'nav.whereToStay': 'Dónde Hospedarse',
    'nav.events': 'Eventos',
    'nav.faq': 'Preguntas Frecuentes',
    'nav.contact': 'Contacto',
    
    // Home Page
    'home.hero.title': 'Cabeceras',
    'home.hero.subtitle': 'La vida cotidiana en una comunidad rural costarricense',
    'home.hero.tagline': 'Una parada significativa cerca de Monteverde',
    'home.whereWeAre.title': 'Dónde Estamos',
    'home.whereWeAre.description': 'Cabeceras está ubicada a 25 minutos de Monteverde, en el camino entre Monteverde y La Fortuna.',
    'home.communityWalk.title': 'Comience con el Recorrido Comunitario',
    'home.communityWalk.description1': 'Pasará por lugares de reunión locales, fincas y miradores, y aprenderá cómo vive y trabaja la gente aquí.',
    'home.communityWalk.description2': 'Solicite un guía local gratuito — jóvenes y mujeres de la comunidad compartiendo su pueblo.',
    'home.communityWalk.learnButton': 'Conozca el Recorrido',
    'home.communityWalk.requestButton': 'Solicitar un Guía',
    'home.moreWays.title': 'Más Formas de Conectar',
    'home.moreWays.description': 'Cocine con familias locales, aprenda artesanías tradicionales, vea el atardecer o pase tiempo donde se reúnen los locales',
    'home.moreWays.photo1': 'Cocinando juntos',
    'home.moreWays.photo2': 'Celebraciones',
    'home.moreWays.button': 'Ver Todas las Experiencias',
    'home.testimonials.title': 'Lo Que Comparten los Visitantes',
    'home.testimonials.subtitle': 'Reflexiones de personas que pasaron tiempo en Cabeceras',
    'home.testimonial1': 'El recorrido comunitario con nuestro guía local fue increíble. Aprendimos mucho sobre la vida real costarricense — desde el cultivo de café hasta las tradiciones locales. Se sintió auténtico y significativo.',
    'home.testimonial2': 'La clase de cocina con Doña Luz fue lo más destacado de nuestro viaje. Hicimos platos tradicionales en su cocina casera y escuchamos historias increíbles. Esto es de lo que debería tratarse viajar.',
    'home.testimonial3': 'El atardecer en el Mirador Finitos fue impresionante, y pasar tiempo en el café Mikancha con los locales fue muy relajante. Cabeceras nos mostró un lado de Costa Rica que nunca hubiéramos encontrado de otra manera.',
    'home.planVisit.title': 'Planifique su Visita',
    'home.planVisit.description': 'Ya sea que esté de paso o se quede un tiempo, Cabeceras le da la bienvenida',
    'home.planVisit.accommodationButton': 'Encontrar Alojamiento',
    'home.planVisit.contactButton': 'Ponerse en Contacto',

    // What to Do Page
    'experiences.hero.title': 'Qué Hacer en Cabeceras',
    'experiences.hero.subtitle': 'Formas de pasar tiempo aquí',
    'experiences.communityWalk.title': 'El Recorrido Comunitario',
    'experiences.communityWalk.description': 'Comience en el Salón Comunal, pase por la escuela y el jardín en la ladera, visite el árbol viejo donde se reúnen los tucanes, suba al mirador y recorra una finca de café. Autoguiado en cualquier momento, o solicite un guía local. Los guías son jóvenes y mujeres de la comunidad que practican inglés y comparten su pueblo.',
    'experiences.communityWalk.duration': '~45 minutos',
    'experiences.communityWalk.difficulty': 'Fácil a Moderado',
    'experiences.communityWalk.aboutButton': 'Sobre el Recorrido',
    'experiences.communityWalk.guideButton': 'Solicitar un Guía',
    'experiences.cooking.title': 'Cocinando con Doña Luz',
    'experiences.cooking.description': 'Únase a Doña Luz en su hogar para hacer empanadas, pan y jugo de caña fresco usando su molino tradicional. Disfrute del café de su finca, vistas a las montañas e historias compartidas a un ritmo relajado. Contacte a Doña Luz directamente por WhatsApp para coordinar un horario. Planifique con 24–48 horas de anticipación cuando sea posible.',
    'experiences.cooking.duration': '3 horas',
    'experiences.cooking.difficulty': 'Todos los niveles',
    'experiences.cooking.button': 'Contactar para Coordinar',
    'experiences.embroidery.title': 'Bordado con Doña Margarita',
    'experiences.embroidery.description': 'Cree su propio recuerdo del bosque nuboso mientras aprende patrones inspirados en la naturaleza costarricense. Doña Margarita y otras mujeres de la comunidad lo guiarán. Contacte a Doña Margarita directamente por WhatsApp para coordinar un horario. Planifique con 24-48 horas de anticipación cuando sea posible.',
    'experiences.embroidery.duration': '2-3 horas',
    'experiences.embroidery.difficulty': 'Todos los niveles',
    'experiences.mikancha.title': 'Mikancha',
    'experiences.mikancha.description': 'Observe partidos de fútbol (mejengas), juegue billar, coma algo y pase tiempo donde los miembros de la comunidad pasan su tiempo libre. No se necesita reservación — solo aparezca y vea quién está.',
    'experiences.mikancha.duration': 'Flexible',
    'experiences.mikancha.difficulty': 'Fácil',
    'experiences.mikancha.note': 'No se necesita reservación — solo pase',
    'experiences.lookout.title': 'Mirador Finitos',
    'experiences.lookout.description': 'Camine por jardines con vistas al valle. Mejor al atardecer cuando el cielo se transforma. No se requiere caminata — el mirador es fácilmente accesible. Donación recomendada: ₡2,000 por persona. No se necesita reservación.',
    'experiences.lookout.duration': '1-2 horas',
    'experiences.lookout.difficulty': 'Fácil',

    // Tour Page
    'tour.hero.title': 'Recorrido Comunitario',
    'tour.hero.subtitle': 'Vea cómo vive y trabaja la gente en Cabeceras',
    'tour.about.title': 'Sobre el Recorrido',
    'tour.about.description1': 'Nuestro recorrido comunitario lo lleva por el corazón de Cabeceras, compartiendo la historia de nuestro pueblo, su gente y cómo vivimos. Aprenda sobre nuestras principales industrias (lecherías y plantaciones de café), cómo funcionan el gobierno local y los comités, y cómo están cambiando las cosas en nuestra comunidad.',
    'tour.about.description2': 'Puede hacer esto como un recorrido autoguiado usando nuestro mapa, pero recomendamos encarecidamente reservar un guía local gratuito. Nuestro programa de guías fue diseñado para ayudar a los jóvenes y mujeres locales a desarrollar confianza, habilidades de liderazgo y adquisición del idioma inglés mientras facilita un intercambio simbiótico entre viajeros y locales.',
    'tour.stats.duration': 'Duración',
    'tour.stats.durationValue': '~45 minutos',
    'tour.stats.difficulty': 'Dificultad',
    'tour.stats.difficultyValue': 'Fácil a Moderado',
    'tour.stats.cost': 'Costo',
    'tour.stats.costValue': 'Gratis',
    'tour.route.title': 'Ruta del Recorrido Autoguiado',
    'tour.route.description': 'Siga estas paradas a su propio ritmo. Busque señales en el camino, o descargue nuestro mapa para uso sin conexión.',
    'tour.stop1.name': 'Salón Comunal',
    'tour.stop1.description': 'Comience su caminata en el centro comunitario, con vistas abiertas del pueblo. Lea sobre la historia de Cabeceras, la vida diaria hoy y oriéntese.',
    'tour.stop2.name': 'Escuela Local',
    'tour.stop2.description': 'Pase por la escuela primaria y aprenda sobre la educación en la comunidad y las vidas de los jóvenes que crecen aquí.',
    'tour.stop3.name': 'Jardín en la Ladera',
    'tour.stop3.description': 'Pase por una ladera ajardinada creada por la comunidad, con la opción de subir para obtener vistas sobre el pueblo.',
    'tour.stop4.name': 'La Iglesia',
    'tour.stop4.description': 'Pase por la iglesia y lea sobre el papel de la religión en la región y la vida comunitaria.',
    'tour.stop5.name': 'El Árbol Viejo',
    'tour.stop5.description': 'Visite un árbol de larga data que ha sido parte de la comunidad durante generaciones. Busque tucanes y otras aves en las ramas, y lea sobre la vida silvestre local y cómo esta área difiere de Monteverde cercano.',
    'tour.stop6.name': 'Mirador Cubiertas',
    'tour.stop6.description': 'Suba a un mirador con vista al valle y las montañas circundantes.',
    'tour.stop7.name': 'Circuito de la Finca de Café',
    'tour.stop7.description': 'Camine por una finca de café y un área boscosa, regresando a su punto de partida. Aprenda sobre la producción de café y su papel en la economía local.',
    'tour.accessibility.title': 'Nota de Accesibilidad',
    'tour.accessibility.description': 'El Circuito de la Finca de Café (parada 7) incluye una sección corta y empinada con terreno irregular. Si es necesario, puede dar la vuelta y regresar por donde vino; la ruta principal permanece completa.',
    'tour.map.title': 'Mapa del Recorrido',
    'tour.map.downloadButton': 'Descargar Mapa',
    'tour.guide.title': '¿Quiere un Guía Local?',
    'tour.guide.description1': 'Jóvenes y mujeres de la comunidad pueden caminar con usted y compartir historias, responder preguntas y ayudarlo a entender lo que está viendo.',
    'tour.guide.description2': 'Los guías son gratuitos — el programa ayuda a los locales a practicar inglés y desarrollar confianza mientras crea intercambios significativos con los visitantes.',
    'tour.guide.button': 'Solicitar un Guía',

    // Where to Stay Page
    'stay.hero.title': 'Dónde Hospedarse',
    'stay.hero.subtitle': 'Una comunidad local tranquila, justo más allá del centro ocupado de Monteverde',
    'stay.camping.name': 'Camping Finito',
    'stay.camping.description': 'Duerma bajo las estrellas, despierte con vistas a las montañas. Instalaciones básicas. Bueno para viajeros con presupuesto limitado y amantes de la naturaleza.',
    'stay.camping.amenity1': 'Sitios para carpas',
    'stay.camping.amenity2': 'Instalaciones compartidas',
    'stay.camping.amenity3': 'Acceso al mirador',
    'stay.casaToucan.name': 'La Casa del Tucán',
    'stay.casaToucan.description': 'Despierte con aves tropicales, coma comidas tradicionales y siéntase parte de la familia. Los anfitriones comparten historias y conocimiento local.',
    'stay.casaToucan.amenity1': 'Comidas caseras',
    'stay.casaToucan.amenity2': 'Habitaciones privadas',
    'stay.casaToucan.amenity3': 'Baños compartidos',
    'stay.casaAlma.name': 'Villa Alma de Campo',
    'stay.casaAlma.description': 'Una casa moderna y cómoda con amplias vistas a las montañas y detalles lujosos y cuidadosos.',
    'stay.casaAlma.amenity1': 'Vistas a las montañas',
    'stay.casaAlma.amenity2': 'Comodidades modernas',
    'stay.casaAlma.amenity3': 'Detalles lujosos',
    'stay.contactButton': 'Contactar para Reservar',
    'stay.testimonials.title': '¿Por Qué Hospedarse en Cabeceras?',
    'stay.testimonials.subtitle': 'Escuche de viajeros que eligieron quedarse en nuestra comunidad',
    'stay.testimonial1': '¡Acampar en Finitos fue una aventura! Despertar con vistas a las montañas y estar tan cerca del mirador fue increíble. Económico e inolvidable.',
    'stay.testimonial2': 'Quedarse en Casa Toucan se sintió como ser parte de la familia. Las comidas caseras fueron increíbles, y aprendimos mucho sobre la vida local. Fue la base perfecta entre Monteverde y La Fortuna.',
    'stay.testimonial3': 'Casa Alma fue un retiro tranquilo después de las multitudes en Monteverde. Las vistas al jardín, las mañanas tranquilas y la hospitalidad genuina nos hicieron extender nuestra estadía por dos noches.',

    // Events Page
    'events.hero.title': 'Eventos Comunitarios',
    'events.intro.description1': 'Estas son reuniones reales que ocurren en Cabeceras como parte de la vida comunitaria cotidiana. Los visitantes son bienvenidos a asistir y experimentar cómo se reúnen los locales.',
    'events.intro.description2': 'Los eventos pueden cambiar o cancelarse. Consulte con nosotros más cerca de su fecha de visita para obtener información actualizada.',
    'events.upcoming.title': 'Próximos Eventos',
    'events.recurring.title': 'Actividades Recurrentes',
    'events.submit.title': 'Miembros de la Comunidad',
    'events.submit.description': '¿Tiene un evento para compartir? Háganos saber sobre próximas reuniones comunitarias, celebraciones o actividades.',
    'events.submit.button': 'Enviar un Evento',
    'events.event1.title': 'Festival de la Cosecha de Café',
    'events.event1.date': '15-17 de diciembre, 2024',
    'events.event1.time': 'Todo el día',
    'events.event1.location': 'Varios lugares en todo el pueblo',
    'events.event1.description': 'Celebración anual de la temporada de cosecha de café. Tours de fincas locales, música tradicional y comidas comunitarias.',
    'events.event2.title': 'Exposición de Arte Juvenil',
    'events.event2.date': '20-25 de marzo, 2025',
    'events.event2.time': '10:00 AM - 6:00 PM',
    'events.event2.location': 'Centro Comunitario',
    'events.event2.description': 'Obras de arte de estudiantes de la escuela local en exhibición. Pinturas, artesanías y proyectos creativos.',
    'events.event3.title': 'Celebración del Día de la Independencia',
    'events.event3.date': '15 de septiembre, 2025',
    'events.event3.time': '9:00 AM - 8:00 PM',
    'events.event3.location': 'Salón Comunal',
    'events.event3.description': 'Festividades del Día de la Independencia de Costa Rica con comida tradicional, música y el desfile de faroles.',
    'events.recurring1.title': 'Mercado Comunitario',
    'events.recurring1.schedule': 'Todos los sábados',
    'events.recurring1.time': '8:00 AM - 2:00 PM',
    'events.recurring1.location': 'Salón Comunal',
    'events.recurring1.description': 'Vendedores locales venden productos frescos, artesanías y productos caseros.',
    'events.recurring2.title': 'Noche de Música Tradicional',
    'events.recurring2.schedule': 'Primer viernes de cada mes',
    'events.recurring2.time': '7:00 PM - 10:00 PM',
    'events.recurring2.location': 'Café Mikancha',
    'events.recurring2.description': 'Presentaciones de música en vivo por músicos locales. Abierto a todos.',
    'events.recurring3.title': 'Reunión Comunitaria',
    'events.recurring3.schedule': 'Segundo martes de cada mes',
    'events.recurring3.time': '6:00 PM',
    'events.recurring3.location': 'Salón Comunal',
    'events.recurring3.description': 'Reunión abierta del pueblo para discutir asuntos comunitarios. Los visitantes son bienvenidos a observar.',

    // FAQ Page
    'faq.hero.title': 'Preguntas Frecuentes',
    'faq.hero.subtitle': 'Todo lo que necesita saber sobre visitar Cabeceras',
    'faq.question1': '¿El recorrido comunitario es realmente gratis?',
    'faq.answer1': 'Sí, es completamente gratis ya que está apoyando a los locales en el desarrollo de capacidades/habilidades importantes. También apreciamos que tenga la curiosidad y se tome el tiempo para aprender sobre nuestro pueblo y nuestra gente. Siéntase libre de dar una pequeña propina a su guía si disfrutó el recorrido, pero no se espera.',
    'faq.question2': '¿Cómo llego a Cabeceras?',
    'faq.answer2': 'Cabeceras está a 25 minutos de Monteverde, en la ruta principal entre Monteverde y La Fortuna. Puede llegar en automóvil o coordinar transporte a través de su alojamiento.',
    'faq.question3': '¿Necesito reservar experiencias con anticipación?',
    'faq.answer3': 'Aunque el recorrido comunitario autoguiado siempre está disponible, recomendamos reservar clases de cocina, talleres y experiencias guiadas con al menos 24-48 horas de anticipación para garantizar disponibilidad. Contáctenos por WhatsApp o correo electrónico para coordinar.',
    'faq.question4': '¿Qué debo traer para el recorrido?',
    'faq.answer4': 'Se recomiendan zapatos cómodos para caminar, protección solar, agua y una cámara. El recorrido implica caminar moderadamente por senderos sin pavimentar. También sugerimos traer billetes pequeños si desea hacer compras en tiendas locales o dejar donaciones.',
    'faq.question5': '¿Cabeceras es adecuada para familias con niños?',
    'faq.answer5': '¡Absolutamente! Cabeceras es muy familiar. Los niños disfrutan interactuar con niños locales, aprender sobre agricultura y explorar la naturaleza. Las clases de cocina y talleres de artesanía son particularmente populares entre las familias.',
    'faq.question6': '¿Cuánto tiempo debo planear pasar en Cabeceras?',
    'faq.answer6': 'La mayoría de los visitantes pasan de 2 a 4 horas en el recorrido comunitario, pero recomendamos quedarse al menos un día completo para experimentar verdaderamente la vida local. Muchos viajeros eligen quedarse una noche en una de nuestras casas de huéspedes para sumergirse completamente.',
    'faq.question7': '¿Qué idiomas se hablan?',
    'faq.answer7': 'El español es el idioma principal, pero muchos miembros de la comunidad hablan inglés básico. Nuestros guías tienen diferentes niveles de inglés, ¡así que invitamos a los huéspedes a venir con una mente abierta! Las diferencias de idioma a menudo conducen a intercambios memorables y creativos.',
    'faq.question8': '¿Cómo beneficia el turismo a la comunidad?',
    'faq.answer8': 'Todas las actividades turísticas apoyan directamente a las familias locales, financian programas de educación juvenil, proporcionan ingresos a mujeres artesanas y ayudan a mantener la infraestructura comunitaria. Practicamos turismo ético liderado por la comunidad que empodera a los residentes.',
    'faq.question9': '¿Puedo ser voluntario en Cabeceras?',
    'faq.answer9': 'Ocasionalmente tenemos oportunidades de voluntariado, especialmente para aquellos con habilidades de enseñanza, agricultura o desarrollo comunitario. Contáctenos para discutir las necesidades actuales y cómo podría contribuir durante su visita.',
    'faq.question10': '¿Cómo es el clima?',
    'faq.answer10': 'Cabeceras tiene un clima tropical y generalmente es más seco y soleado que Monteverde, mientras que es más fresco que La Fortuna debido a su elevación. Los días suelen ser cálidos y cómodos, con mañanas y tardes más frescas.',
    'faq.question11': '¿Hay cajeros automáticos o bancos en Cabeceras?',
    'faq.answer11': 'Cabeceras es un pueblo pequeño sin cajeros automáticos ni bancos. Recomendamos traer efectivo de Monteverde o La Fortuna. Algunos alojamientos y experiencias aceptan tarjetas de crédito, pero se prefiere el efectivo.',
    'faq.question12': '¿Es seguro visitar Cabeceras?',
    'faq.answer12': 'Sí, Cabeceras es una comunidad muy segura. Como en cualquier lugar, use el sentido común con sus pertenencias. La comunidad es acogedora y cuida a los visitantes. Nuestros guías y anfitriones ayudarán a garantizar que tenga una experiencia segura y agradable.',
    'faq.stillQuestions.title': '¿Todavía Tiene Preguntas?',
    'faq.stillQuestions.description': '¡Estamos aquí para ayudar! Contáctenos y estaremos encantados de responder cualquier pregunta sobre visitar Cabeceras.',
    'faq.stillQuestions.button': 'Ponerse en Contacto',

    // Contact Page
    'contact.hero.title': 'Ponerse en Contacto',
    'contact.hero.subtitle': '¿Preguntas sobre visitar Cabeceras?',
    'contact.form.title': 'Enviar un Mensaje',
    'contact.form.name': 'Nombre',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.message': 'Mensaje',
    'contact.form.namePlaceholder': 'Su nombre',
    'contact.form.emailPlaceholder': 'su@correo.com',
    'contact.form.messagePlaceholder': '¿Qué le gustaría saber?',
    'contact.form.submitButton': 'Enviar Mensaje',
    'contact.form.nameError': 'El nombre es requerido',
    'contact.form.emailError': 'El correo electrónico es requerido',
    'contact.form.emailInvalid': 'Por favor ingrese un correo electrónico válido',
    'contact.form.messageError': 'El mensaje es requerido',
    'contact.form.successMessage': '¡Gracias por su mensaje! Le responderemos pronto.',
    'contact.other.title': 'Otras Formas de Contactarnos',
    'contact.email.title': 'Correo Electrónico',
    'contact.email.description': 'Típicamente respondemos dentro de 24 horas',
    'contact.whatsapp.title': 'WhatsApp',
    'contact.whatsapp.description': 'La forma más rápida de contactarnos, especialmente para reservar guías o verificar disponibilidad',
    'contact.whatsapp.button': 'Mensaje por WhatsApp',
    'contact.askAbout.title': 'Sobre Qué Preguntar',
    'contact.askAbout.item1': 'Disponibilidad de guías para el recorrido comunitario',
    'contact.askAbout.item2': 'Reservar clases de cocina o bordado',
    'contact.askAbout.item3': 'Recomendaciones de alojamiento',
    'contact.askAbout.item4': 'Transporte y direcciones',
    'contact.askAbout.item5': 'Eventos o actividades actuales',

    // Footer
    'footer.description': 'Experiencias costarricenses auténticas que empoderan a nuestra comunidad y crean conexiones significativas con los viajeros.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.connect': 'Conéctese con Nosotros',
    'footer.copyright': 'Turismo Comunitario Cabeceras. Todos los derechos reservados.',
    'footer.tagline': 'Construido con amor para el intercambio cultural auténtico.',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
